### ISSUE TITLE
Windows issue with ..

### ISSUE THREAD

**Issue by chrismcv** [sun-zheng-an/gulp-shell#50]
Hi, 
I think I'm seeing an issue in windows with '..' is not recognized as an internal or external command,

Here is the gulp file.
```
var gulp = require('gulp');
var shell = require('gulp-shell');
var handleErrors = require('../util/handleErrors');

gulp.task('jshint', shell.task([
  '../node_modules/.bin/jsxhint --harmony "../src/**" "./src/app/**" --exclude ../src/utils/modernizr.custom.js'
])).on('error', handleErrors);

```
and the output.
```
chris@C005 /e/code/material-ui/docs (master)
$ gulp
[13:41:36] Using gulpfile e:\code\material-ui\docs\gulpfile.js
[13:41:36] Starting 'setWatch'...
[13:41:36] Finished 'setWatch' after 64 μs
[13:41:36] Starting 'jshint'...
[13:41:36] Starting 'markup'...
[13:41:36] Starting 'fontIcons'...
[13:41:36] Starting 'css'...
'..' is not recognized as an internal or external command,
operable program or batch file.
[13:41:36] 'jshint' errored after 47 ms
[13:41:36] Error in plugin 'gulp-shell'
Message:
    Command `../node_modules/.bin/jsxhint --verbose --harmony "../src/**" "./src/app/**" --exclude ../src/utils/modernizr.custom.js` failed with exit code 1
[13:41:36] Finished 'css' after 40 ms
[13:41:36] Finished 'markup' after 62 ms
[13:41:36] Finished 'fontIcons' after 63 ms
```

Running manually on the shell is fine.
```
chris@C005 /e/code//material-ui/docs (master)
$ ../node_modules/.bin/jsxhint --harmony "../src/**" "./src/app/**" --exclude ../src/utils/modernizr.custom.js
```

Any suggestions would be most welcome.

Thanks, 
Chris

**Comment by inoc603** [comment]
I'm getting kind of the same error. The problem is with the slashes.

On windows, when you write a path in the command line you should use `\` instead of `/`. As your error message shows:

> '..' is not recognized as an internal or external command

That means rather than take `../node_modules/.bin/jsxhint` as the command, the command line stopped parsing at the first `/`.

Replacing `/` with `\\` should make your task run on windows. For better cross-platform experience you can check your platform in your task, and replace the slashes if needed.

Or maybe we should add the checking to this module, I'll try make a PR.

**Comment by chrismcv** [comment]
```"../node_modules/.bin/jsxhint" .....``` works
